/*   DeBR - GeBR Designer
 *   Copyright (C) 2007-2009 GeBR core team (http://www.gebrproject.com/)
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

G_BEGIN_DECLS

const gchar * menu_dialog_save_def = 
"<?xml version=\"1.0\"?>"
"<interface>"
  "<!-- interface-requires gtk+ 2.12 -->"
  "<!-- interface-naming-policy project-wide -->"
  "<object class=\"GtkDialog\" id=\"dialog1\">"
    "<property name=\"border_width\">5</property>"
    "<property name=\"type_hint\">normal</property>"
    "<property name=\"has_separator\">False</property>"
    "<property name=\"resizable\">False</property>"
    "<property name=\"modal\">True</property>"
    "<property name=\"window_position\">center-on-parent</property>"
    "<child internal-child=\"vbox\">"
      "<object class=\"GtkVBox\" id=\"dialog-vbox1\">"
        "<property name=\"visible\">True</property>"
        "<property name=\"orientation\">vertical</property>"
        "<property name=\"spacing\">2</property>"
        "<child>"
          "<object class=\"GtkHBox\" id=\"hbox1\">"
            "<property name=\"visible\">True</property>"
            "<property name=\"spacing\">10</property>"
            "<child>"
              "<object class=\"GtkImage\" id=\"image1\">"
                "<property name=\"visible\">True</property>"
                "<property name=\"yalign\">0</property>"
                "<property name=\"stock\">gtk-dialog-warning</property>"
                "<property name=\"icon-size\">6</property>"
              "</object>"
              "<packing>"
                "<property name=\"expand\">False</property>"
                "<property name=\"position\">0</property>"
              "</packing>"
            "</child>"
            "<child>"
              "<object class=\"GtkVBox\" id=\"vbox1\">"
                "<property name=\"visible\">True</property>"
                "<property name=\"orientation\">vertical</property>"
                "<property name=\"spacing\">10</property>"
                "<child>"
                  "<object class=\"GtkLabel\" id=\"label1\">"
                    "<property name=\"visible\">True</property>"
                    "<property name=\"xalign\">0</property>"
                    "<property name=\"label\" translatable=\"yes\">&lt;span weight=\"bold\" size=\"large\"&gt;There are menus with unsaved changes. Save changes before closing?&lt;/span&gt;</property>"
                    "<property name=\"use_markup\">True</property>"
                    "<property name=\"wrap\">True</property>"
                  "</object>"
                  "<packing>"
                    "<property name=\"expand\">False</property>"
                    "<property name=\"position\">0</property>"
                  "</packing>"
                "</child>"
                "<child>"
                  "<object class=\"GtkLabel\" id=\"label2\">"
                    "<property name=\"visible\">True</property>"
                    "<property name=\"xalign\">0</property>"
                    "<property name=\"label\" translatable=\"yes\">Select the menus you want to save:</property>"
                  "</object>"
                  "<packing>"
                    "<property name=\"expand\">False</property>"
                    "<property name=\"position\">1</property>"
                  "</packing>"
                "</child>"
                "<child>"
                  "<object class=\"GtkScrolledWindow\" id=\"scrolledwindow1\">"
                    "<property name=\"visible\">True</property>"
                    "<property name=\"can_focus\">True</property>"
                    "<property name=\"hscrollbar_policy\">automatic</property>"
                    "<property name=\"vscrollbar_policy\">automatic</property>"
                    "<child>"
                      "<object class=\"GtkViewport\" id=\"viewport1\">"
                        "<property name=\"visible\">True</property>"
                        "<property name=\"resize_mode\">queue</property>"
                        "<child>"
                          "<object class=\"GtkTreeView\" id=\"treeview1\">"
                            "<property name=\"visible\">True</property>"
                            "<property name=\"can_focus\">True</property>"
                            "<property name=\"model\">liststore1</property>"
                            "<property name=\"search_column\">0</property>"
                          "</object>"
                        "</child>"
                      "</object>"
                    "</child>"
                  "</object>"
                "</child>"
                "<child>"
                  "<object class=\"GtkLabel\" id=\"label3\">"
                    "<property name=\"visible\">True</property>"
                    "<property name=\"xalign\">0</property>"
                    "<property name=\"label\" translatable=\"yes\">If you don't save, all your changes will be permanently lost.</property>"
                  "</object>"
                  "<packing>"
                    "<property name=\"expand\">False</property>"
                    "<property name=\"position\">3</property>"
                  "</packing>"
                "</child>"
              "</object>"
              "<packing>"
                "<property name=\"position\">1</property>"
              "</packing>"
            "</child>"
          "</object>"
          "<packing>"
            "<property name=\"position\">1</property>"
          "</packing>"
        "</child>"
        "<child internal-child=\"action_area\">"
          "<object class=\"GtkHButtonBox\" id=\"dialog-action_area1\">"
            "<property name=\"visible\">True</property>"
            "<property name=\"homogeneous\">True</property>"
            "<property name=\"layout_style\">end</property>"
            "<child>"
              "<object class=\"GtkButton\" id=\"closeBtn\">"
                "<property name=\"label\" translatable=\"yes\">Close _without saving</property>"
                "<property name=\"visible\">True</property>"
                "<property name=\"can_focus\">True</property>"
                "<property name=\"receives_default\">True</property>"
                "<property name=\"use_underline\">True</property>"
                "<property name=\"image\">image2</property>"
              "</object>"
              "<packing>"
                "<property name=\"expand\">False</property>"
                "<property name=\"fill\">False</property>"
                "<property name=\"position\">0</property>"
              "</packing>"
            "</child>"
            "<child>"
              "<object class=\"GtkButton\" id=\"cancelBtn\">"
                "<property name=\"label\">gtk-cancel</property>"
                "<property name=\"visible\">True</property>"
                "<property name=\"can_focus\">True</property>"
                "<property name=\"receives_default\">True</property>"
                "<property name=\"use_stock\">True</property>"
              "</object>"
              "<packing>"
                "<property name=\"expand\">False</property>"
                "<property name=\"fill\">False</property>"
                "<property name=\"position\">1</property>"
              "</packing>"
            "</child>"
            "<child>"
              "<object class=\"GtkButton\" id=\"saveBtn\">"
                "<property name=\"label\">gtk-save</property>"
                "<property name=\"visible\">True</property>"
                "<property name=\"can_focus\">True</property>"
                "<property name=\"can_default\">True</property>"
                "<property name=\"has_default\">True</property>"
                "<property name=\"receives_default\">True</property>"
                "<property name=\"use_stock\">True</property>"
              "</object>"
              "<packing>"
                "<property name=\"expand\">False</property>"
                "<property name=\"fill\">False</property>"
                "<property name=\"position\">2</property>"
              "</packing>"
            "</child>"
          "</object>"
          "<packing>"
            "<property name=\"expand\">False</property>"
            "<property name=\"pack_type\">end</property>"
            "<property name=\"position\">0</property>"
          "</packing>"
        "</child>"
      "</object>"
    "</child>"
    "<action-widgets>"
      "<action-widget response=\"3\">closeBtn</action-widget>"
      "<action-widget response=\"2\">cancelBtn</action-widget>"
      "<action-widget response=\"1\">saveBtn</action-widget>"
    "</action-widgets>"
  "</object>"
  "<object class=\"GtkListStore\" id=\"liststore1\">"
    "<columns>"
      "<column type=\"gboolean\"/>"
      "<column type=\"gchararray\"/>"
      "<column type=\"gpointer\"/>"
    "</columns>"
  "</object>"
  "<object class=\"GtkImage\" id=\"image2\">"
    "<property name=\"visible\">True</property>"
    "<property name=\"stock\">gtk-close</property>"
  "</object>"
"</interface>";

G_END_DECLS
